title: "Patriots Nation"
description: "Latest news, updates, and fan stories"

url: "https://patriotsnation.page"
baseurl: ""

plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

theme: jekyll-theme-primer