title: "Patriots Nation"
description: "Latest news, updates, and fan stories"
url: "https://bshroats5.github.io
baseurl: "/Patriots_Nation" 

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"
