title: "Patriots Nation"
description: "Latest news, updates, and fan stories"

url: "https://patriotsnation.page"
baseurl: ""

plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

# Add this to make pagination work on blog.md
plugins:
  - jekyll-paginate

  # Google Analytics plugin
  - jekyll-google-analytics
google_analytics: "G-ZM02M55KR5"