name: Tweet New Posts

on:
  push:
    paths:
      - '_posts/*.md'

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Get new post info
        id: post
        run: |
          # Get the newest post file
          POST=$(git diff --name-only HEAD^ HEAD | grep _posts | head -1)
          if [ -n "$POST" ]; then
            TITLE=$(grep "^title:" "$POST" | cut -d'"' -f2)
            DATE=$(echo $POST | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}')
            SLUG=$(echo $POST | sed 's/_posts\///' | sed 's/.md$//')
            URL="https://patriotsnation.page/blog/${DATE//-/\/}/${SLUG#*-*-*-}"
            echo "title=$TITLE" >> $GITHUB_OUTPUT
            echo "url=$URL" >> $GITHUB_OUTPUT
          fi
      
      - name: Tweet
        if: steps.post.outputs.title != ''
        uses: ethomson/send-tweet-action@v1
        with:
          status: |
            New blog post: ${{ steps.post.outputs.title }}
            
            ${{ steps.post.outputs.url }}
            
            #OneBigTeam #LoveTheLogo
          consumer-key: ${{ secrets.TWITTER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_SECRET }}